version: '3.5'

services:
  django_main_db:
    image: postgres
    environment:
      - DOCKER=True
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Iamgenius
      - POSTGRES_DB=django_main
    ports:
      - "54321:5432"
    networks:
      - net
    volumes:
      - ../pgdata/pgdata:/var/lib/postgresql/data_docker/pgdata_docker
  django_main:
    build: django_main
    image: django_main
    command: ["bash", "-c", "sleep 15; python manage.py migrate --noinput; sleep 10; python -c django_main/create_superuser.py; sleep 10;  python manage.py runserver 0.0.0.0:8000;"]
    volumes:
      - .:/django_main
    ports:
      - "8000:8000"
    depends_on:
      - django_main_db
    networks:
     - net

networks:
  net:
    driver: bridge
